version: '3.9'

services:
  app:
    build: .
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "/pop_culture/bin/popCulture"]
    restart: always

  mysql:
    container_name: mysql_database
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pop_culture
      - MYSQL_USER=pop_user
      - MYSQL_PASSWORD=123456789
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root




